### Open Flights Data Wrangling

To practice, you are going to wrangle data from OpenFlights.  You can read about it here: 

http://openflights.org/data.html

This includes three main files, one for each airport, one for each airline, and one for each route.  They can be merged or joined with the appropriate fields.  I have modified the files slightly to include a header row in the .dat files, which makes it a bit easier for you.  

You are required to work through the problems below.  This may take some time.  Be persistent, and ask questions or seek help as needed.

In [5]:
import pandas as pd
import numpy as np

In [6]:
# These files use \N as a missing value indicator.  When reading the CSVs, we will tell
# it to use that value as missing or NA.  The double backslash is required because
# otherwise it will interpret \N as a carriage return. 

# Read in the airports data.
airports = pd.read_csv("data/airports.dat", header=None, na_values='\\N')
airports.columns = ["id", "name", "city", "country", "iata", "icao", "latitude", "longitude", "altitude","timezone", "dst", "tz", "type", "source"]

# Read in the airlines data.
airlines = pd.read_csv("data/airlines.dat", header=None, na_values='\\N')
airlines.columns = ["id", "name", "alias", "iata", "icao", "callsign", "country", "active"]

# Read in the routes data.
routes = pd.read_csv("data/routes.dat", header=None, na_values='\\N')
routes.columns = ["airline", "airline_id", "source", "source_id", "dest", "dest_id", "codeshare", "stops", "equipment"]

1) Start by seeing what's in the data.  What columns are there?  What data types are the columns?  

Remember, 'object' means it is a string, while the numerical values can be floats or ints.  Sometimes you will have problems if it reads numeric data in as strings.  If that happens, you can use the function .astype() to convert it.  Look it up in the pandas API to get more details

In [7]:
import pandas as pd
import numpy as np

In [8]:
airlines = pd.read_csv("data/airlines.dat", header=None, na_values='\\N')
airlines.columns = ["id", "name", "alias", "iata", "icao", "callsign", "country", "active"]
airlines

,id,name,alias,iata,icao,callsign,country,active
0,-1,Unknown,NaN,-,NaN,NaN,NaN,Y
1,1,Private flight,NaN,-,NaN,NaN,NaN,Y
2,2,135 Airways,NaN,NaN,GNL,GENERAL,United States,N
3,3,1Time Airline,NaN,1T,RNX,NEXTIME,South Africa,Y
4,4,2 Sqn No 1 Elementary Flying Training School,NaN,NaN,WYT,NaN,United Kingdom,N
5,5,213 Flight Unit,NaN,NaN,TFU,NaN,Russia,N
6,6,223 Flight Unit State Airline,NaN,NaN,CHD,CHKALOVSK-AVIA,Russia,N
7,7,224th Flight Unit,NaN,NaN,TTF,CARGO UNIT,Russia,N
8,8,247 Jet Ltd,NaN,NaN,TWF,CLOUD RUNNER,United Kingdom,N
9,9,3D Aviation,NaN,NaN,SEC,SECUREX,United States,N
10,10,40-Mile Air,NaN,Q5,MLA,MILE-AIR,United States,Y
11,11,4D Air,NaN,NaN,QRT,QUARTET,Thailand,N
12,12,611897 Alberta Limited,NaN,NaN,THD,DONUT,Canada,N
13,13,Ansett Australia,NaN,AN,AAA,ANSETT,Australia,Y
14,14,Abacus International,NaN,1B,NaN,NaN,Singapore,Y
15,15,Abelag Aviation,NaN,W9,AAB,ABG,Belgium,N
16,16,Army Air Corps,NaN,NaN,AAC,ARMYAIR,United Kingdom,N
17,17,Aero Aviation Centre Ltd.,NaN,NaN,AAD,SUNRISE,Canada,N
18,18,Aero Servicios Ejecutivos Internacionales,NaN,NaN,SII,ASEISA,Mexico,N
19,19,Aero Biniza,NaN,NaN,BZS,BINIZA,Mexico,N
20,20,Aero Albatros,NaN,NaN,ABM,ALBATROS ESPANA,Spain,N
21,21,Aigle Azur,NaN,ZI,AAF,AIGLE AZUR,France,Y
22,22,Aloha Airlines,NaN,AQ,AAH,ALOHA,United States,Y
23,23,Alaska Island Air,NaN,NaN,AAK,ALASKA ISLAND,United States,N
24,24,American Airlines,NaN,AA,AAL,AMERICAN,United States,Y
25,25,Aviation Management Corporation,NaN,NaN,AAM,AM CORP,United States,N
26,26,Atlantis Airlines (USA),NaN,NaN,AAO,ATLANTIS AIR,United States,N
27,27,Aerovista Airlines,NaN,NaN,AAP,AEROVISTA GROUP,United Arab Emirates,N
28,28,Asiana Airlines,NaN,OZ,AAR,ASIANA,Republic of Korea,Y
29,29,Askari Aviation,NaN,4K,AAS,AL-AAS,Pakistan,Y
...,...,...,...,...,...,...,...,...
6132,20827,Fly France,Fly France,FF,FRF,NaN,France,Y
6133,20875,Jota Aviation,NaN,NaN,ENZ,ENZO,United Kingdom,Y
6134,20881,Europe Jet,Europe Jet,EX,EU9,NaN,France,Y
6135,20923,COBALT,COBALT,NaN,FCB,COBALT,Cyprus,Y
6136,20931,Southern Airways Express,Sun Air Express,NaN,LTD,LIGHTSPEED,United States,Y
6137,20961,Deutsche Luftverkehrsgesellschaft (DLT),NaN,DW,DWD,NaN,Germany,N
6138,20962,Orenburzhie,NaN,NaN,ORG,NaN,Russia,Y
6139,20963,Atlantic Air Cargo,NaN,K3,NaN,NaN,United States,N
6140,20976,World Scale Airlines,World Scale,W3,WSS,NaN,United States,Y
6141,20978,All America US,All America US,AG,SSA,NaN,United States,Y
6142,20986,University of Birmingham Air Squadron (RAF),8AEF RAF,NaN,UAY,UAY,United Kingdom,Y
6143,20991,Choice Airways,NaN,NaN,CSX,NaN,United States,Y
6144,20994,Aruba Airlines,NaN,NaN,ARU,NaN,Aruba,Y
6145,20995,BudgetAir,BudgetAir,1K,BG1,NaN,Germany,Y
6146,20996,Dynamic Airways,NaN,NaN,DYA,NaN,United States,Y
6147,21012,Fly One,Fly One,F5,FI5,NaN,Moldova,Y
6148,21021,Nordica,NaN,EE,NaN,REVAL,Estonia,Y
6149,21036,Tez Jet Airlines,NaN,NaN,TEZ,NaN,Kyrgyzstan,Y
6150,21043,Kush Air,NaN,NaN,KUH,NaN,South Sudan,Y
6151,21056,Dummy,NaN,0E,NaN,NaN,France,N
6152,21124,ViaAir,Charter Air Transport,NaN,SRY,Stingray,United States,Y
6153,21131,All America BOPY,All America BOPY,0P,PYB,BOPY,Paraguay,Y
6154,21179,Thai Vietjet Air,NaN,NaN,TVJ,THAIVIET JET,Thailand,Y
6155,21181,Air Andaman (2Y),NaN,2Y,AOW,AIR ANDAMAN,Thailand,N
6156,21240,TDA Toa Domestic Airlines,TDA,NaN,TDA,Toa Domes,Japan,N
6157,21248,GX Airlines,NaN,NaN,CBG,SPRAY,China,Y
6158,21251,Lynx Aviation (L3/SSX),NaN,NaN,SSX,Shasta,United States,N
6159,21268,Jetgo Australia,NaN,JG,NaN,NaN,Australia,Y
6160,21270,Air Carnival,NaN,2S,NaN,NaN,India,Y
6161,21317,Svyaz Rossiya,Russian Commuter,7R,SJM,RussianConnecty,Russia,Y

2) Select just the routes that go to or from Lexington Bluegrass Airport, and store them in their own dataframe.  

The airport code is LEX.  You should have a much smaller dataframe.  How many inbound routes and how many outbound routes are there?

In [9]:
lex_routes = routes[(routes['source']=="LEX")]
lex_routes = pd.merge(lex_routes, airports, left_on='source_id', right_on='id', how='left')

In [10]:
lex_routes = pd.merge(lex_routes, airports, 
                      left_on='dest_id', 
                      right_on='id', 
                      how='left', 
                      suffixes=['_source','_dest'])
lex_routes

,airline,airline_id,source_x,source_id,dest,dest_id,codeshare,stops,equipment,id_source,...,iata_dest,icao_dest,latitude_dest,longitude_dest,altitude_dest,timezone_dest,dst_dest,tz_dest,type_dest,source
0,9E,3976.0,LEX,4017.0,ATL,3682.0,NaN,0,CRJ,4017,...,ATL,KATL,33.636700,-84.428101,1026,-5.0,A,America/New_York,airport,OurAirports
1,AA,24.0,LEX,4017.0,CLT,3876.0,Y,0,CR7 CRJ,4017,...,CLT,KCLT,35.214001,-80.943100,748,-5.0,A,America/New_York,airport,OurAirports
2,AA,24.0,LEX,4017.0,DFW,3670.0,Y,0,ERD ER4,4017,...,DFW,KDFW,32.896801,-97.038002,607,-6.0,A,America/Chicago,airport,OurAirports
3,AA,24.0,LEX,4017.0,ORD,3830.0,Y,0,ERD ER4,4017,...,ORD,KORD,41.978600,-87.904800,672,-6.0,A,America/Chicago,airport,OurAirports
4,AF,137.0,LEX,4017.0,ATL,3682.0,Y,0,CRJ CR9,4017,...,ATL,KATL,33.636700,-84.428101,1026,-5.0,A,America/New_York,airport,OurAirports
5,DL,2009.0,LEX,4017.0,ATL,3682.0,NaN,0,M88 717,4017,...,ATL,KATL,33.636700,-84.428101,1026,-5.0,A,America/New_York,airport,OurAirports
6,DL,2009.0,LEX,4017.0,DCA,3520.0,Y,0,CRJ,4017,...,DCA,KDCA,38.852100,-77.037697,15,-5.0,A,America/New_York,airport,OurAirports
7,DL,2009.0,LEX,4017.0,DTW,3645.0,Y,0,CR7 CRJ CR9,4017,...,DTW,KDTW,42.212399,-83.353401,645,-5.0,A,America/New_York,airport,OurAirports
8,DL,2009.0,LEX,4017.0,LGA,3697.0,NaN,0,ERJ,4017,...,LGA,KLGA,40.777199,-73.872597,21,-5.0,A,America/New_York,airport,OurAirports
9,DL,2009.0,LEX,4017.0,MSP,3858.0,Y,0,CRJ,4017,...,MSP,KMSP,44.882000,-93.221802,841,-6.0,A,America/Chicago,airport,OurAirports
10,G4,35.0,LEX,4017.0,FLL,3533.0,NaN,0,M80,4017,...,FLL,KFLL,26.072599,-80.152702,9,-5.0,A,America/New_York,airport,OurAirports
11,G4,35.0,LEX,4017.0,PGD,7056.0,NaN,0,M80,4017,...,PGD,KPGD,26.920200,-81.990501,26,-5.0,A,America/New_York,airport,OurAirports
12,G4,35.0,LEX,4017.0,PIE,3617.0,NaN,0,320,4017,...,PIE,KPIE,27.910200,-82.687401,11,-5.0,A,America/New_York,airport,OurAirports
13,G4,35.0,LEX,4017.0,SFB,4167.0,NaN,0,M80 320,4017,...,SFB,KSFB,28.777599,-81.237503,55,-5.0,A,America/New_York,airport,OurAirports
14,KL,3090.0,LEX,4017.0,ATL,3682.0,Y,0,CR9 CRJ,4017,...,ATL,KATL,33.636700,-84.428101,1026,-5.0,A,America/New_York,airport,OurAirports
15,UA,5209.0,LEX,4017.0,IAH,3550.0,Y,0,ERJ,4017,...,IAH,KIAH,29.984400,-95.341400,97,-6.0,A,America/Chicago,airport,OurAirports
16,UA,5209.0,LEX,4017.0,ORD,3830.0,Y,0,ERJ CRJ,4017,...,ORD,KORD,41.978600,-87.904800,672,-6.0,A,America/Chicago,airport,OurAirports
17,US,5265.0,LEX,4017.0,CLT,3876.0,NaN,0,CR7,4017,...,CLT,KCLT,35.214001,-80.943100,748,-5.0,A,America/New_York,airport,OurAirports
18,US,5265.0,LEX,4017.0,DFW,3670.0,NaN,0,ERD,4017,...,DFW,KDFW,32.896801,-97.038002,607,-6.0,A,America/Chicago,airport,OurAirports
19,US,5265.0,LEX,4017.0,ORD,3830.0,Y,0,ERD ER4,4017,...,ORD,KORD,41.978600,-87.904800,672,-6.0,A,America/Chicago,airport,OurAirports

3) Now let's look at which airlines operate in and out of Lexington.  To do this, you need to merge the airline dataframe to the route dataframe.  

How many routes does each airline have?  The value_counts() method may be useful for answering this question.

In [14]:
airline_LEX= pd.merge(lex_routes, airlines, left_on='airline_id',right_on='id')
airline_LEX

,airline,airline_id,source_x,source_id,dest,dest_id,codeshare,stops,equipment,id_source,...,type_dest,source,id,name,alias,iata,icao,callsign,country,active
0,9E,3976.0,LEX,4017.0,ATL,3682.0,NaN,0,CRJ,4017,...,airport,OurAirports,3976,Pinnacle Airlines,NaN,9E,FLG,FLAGSHIP,United States,Y
1,AA,24.0,LEX,4017.0,CLT,3876.0,Y,0,CR7 CRJ,4017,...,airport,OurAirports,24,American Airlines,NaN,AA,AAL,AMERICAN,United States,Y
2,AA,24.0,LEX,4017.0,DFW,3670.0,Y,0,ERD ER4,4017,...,airport,OurAirports,24,American Airlines,NaN,AA,AAL,AMERICAN,United States,Y
3,AA,24.0,LEX,4017.0,ORD,3830.0,Y,0,ERD ER4,4017,...,airport,OurAirports,24,American Airlines,NaN,AA,AAL,AMERICAN,United States,Y
4,AF,137.0,LEX,4017.0,ATL,3682.0,Y,0,CRJ CR9,4017,...,airport,OurAirports,137,Air France,NaN,AF,AFR,AIRFRANS,France,Y
5,DL,2009.0,LEX,4017.0,ATL,3682.0,NaN,0,M88 717,4017,...,airport,OurAirports,2009,Delta Air Lines,NaN,DL,DAL,DELTA,United States,Y
6,DL,2009.0,LEX,4017.0,DCA,3520.0,Y,0,CRJ,4017,...,airport,OurAirports,2009,Delta Air Lines,NaN,DL,DAL,DELTA,United States,Y
7,DL,2009.0,LEX,4017.0,DTW,3645.0,Y,0,CR7 CRJ CR9,4017,...,airport,OurAirports,2009,Delta Air Lines,NaN,DL,DAL,DELTA,United States,Y
8,DL,2009.0,LEX,4017.0,LGA,3697.0,NaN,0,ERJ,4017,...,airport,OurAirports,2009,Delta Air Lines,NaN,DL,DAL,DELTA,United States,Y
9,DL,2009.0,LEX,4017.0,MSP,3858.0,Y,0,CRJ,4017,...,airport,OurAirports,2009,Delta Air Lines,NaN,DL,DAL,DELTA,United States,Y
10,G4,35.0,LEX,4017.0,FLL,3533.0,NaN,0,M80,4017,...,airport,OurAirports,35,Allegiant Air,NaN,G4,AAY,ALLEGIANT,United States,Y
11,G4,35.0,LEX,4017.0,PGD,7056.0,NaN,0,M80,4017,...,airport,OurAirports,35,Allegiant Air,NaN,G4,AAY,ALLEGIANT,United States,Y
12,G4,35.0,LEX,4017.0,PIE,3617.0,NaN,0,320,4017,...,airport,OurAirports,35,Allegiant Air,NaN,G4,AAY,ALLEGIANT,United States,Y
13,G4,35.0,LEX,4017.0,SFB,4167.0,NaN,0,M80 320,4017,...,airport,OurAirports,35,Allegiant Air,NaN,G4,AAY,ALLEGIANT,United States,Y
14,KL,3090.0,LEX,4017.0,ATL,3682.0,Y,0,CR9 CRJ,4017,...,airport,OurAirports,3090,KLM Royal Dutch Airlines,NaN,KL,KLM,KLM,Netherlands,Y
15,UA,5209.0,LEX,4017.0,IAH,3550.0,Y,0,ERJ,4017,...,airport,OurAirports,5209,United Airlines,NaN,UA,UAL,UNITED,United States,Y
16,UA,5209.0,LEX,4017.0,ORD,3830.0,Y,0,ERJ CRJ,4017,...,airport,OurAirports,5209,United Airlines,NaN,UA,UAL,UNITED,United States,Y
17,US,5265.0,LEX,4017.0,CLT,3876.0,NaN,0,CR7,4017,...,airport,OurAirports,5265,US Airways,NaN,US,USA,U S AIR,United States,Y
18,US,5265.0,LEX,4017.0,DFW,3670.0,NaN,0,ERD,4017,...,airport,OurAirports,5265,US Airways,NaN,US,USA,U S AIR,United States,Y
19,US,5265.0,LEX,4017.0,ORD,3830.0,Y,0,ERD ER4,4017,...,airport,OurAirports,5265,US Airways,NaN,US,USA,U S AIR,United States,Y

4) It looks like there are some international airlines with Lexington routes.  To look at how many routes they have, create a new column in your dataframe called 'International', which is set to Y for an overseas airline and N for a domestic airline.  Calculate the percent of routes with an overseas airline.

In [26]:
is_International= []
for domestic_static in airline_LEX['country']=='United states':
    if domestic_static:
         is_International.append('N')
    else:
        is_International.append('Y')
In_airline_LEX= airline_LEX.assign(Intern=is_International)
In_airline_LEX

,airline,airline_id,source_x,source_id,dest,dest_id,codeshare,stops,equipment,id_source,...,id,name,alias,iata,icao,callsign,country,active,International,Intern
0,9E,3976.0,LEX,4017.0,ATL,3682.0,NaN,0,CRJ,4017,...,3976,Pinnacle Airlines,NaN,9E,FLG,FLAGSHIP,United States,Y,False,Y
1,AA,24.0,LEX,4017.0,CLT,3876.0,Y,0,CR7 CRJ,4017,...,24,American Airlines,NaN,AA,AAL,AMERICAN,United States,Y,False,Y
2,AA,24.0,LEX,4017.0,DFW,3670.0,Y,0,ERD ER4,4017,...,24,American Airlines,NaN,AA,AAL,AMERICAN,United States,Y,False,Y
3,AA,24.0,LEX,4017.0,ORD,3830.0,Y,0,ERD ER4,4017,...,24,American Airlines,NaN,AA,AAL,AMERICAN,United States,Y,False,Y
4,AF,137.0,LEX,4017.0,ATL,3682.0,Y,0,CRJ CR9,4017,...,137,Air France,NaN,AF,AFR,AIRFRANS,France,Y,False,Y
5,DL,2009.0,LEX,4017.0,ATL,3682.0,NaN,0,M88 717,4017,...,2009,Delta Air Lines,NaN,DL,DAL,DELTA,United States,Y,False,Y
6,DL,2009.0,LEX,4017.0,DCA,3520.0,Y,0,CRJ,4017,...,2009,Delta Air Lines,NaN,DL,DAL,DELTA,United States,Y,False,Y
7,DL,2009.0,LEX,4017.0,DTW,3645.0,Y,0,CR7 CRJ CR9,4017,...,2009,Delta Air Lines,NaN,DL,DAL,DELTA,United States,Y,False,Y
8,DL,2009.0,LEX,4017.0,LGA,3697.0,NaN,0,ERJ,4017,...,2009,Delta Air Lines,NaN,DL,DAL,DELTA,United States,Y,False,Y
9,DL,2009.0,LEX,4017.0,MSP,3858.0,Y,0,CRJ,4017,...,2009,Delta Air Lines,NaN,DL,DAL,DELTA,United States,Y,False,Y
10,G4,35.0,LEX,4017.0,FLL,3533.0,NaN,0,M80,4017,...,35,Allegiant Air,NaN,G4,AAY,ALLEGIANT,United States,Y,False,Y
11,G4,35.0,LEX,4017.0,PGD,7056.0,NaN,0,M80,4017,...,35,Allegiant Air,NaN,G4,AAY,ALLEGIANT,United States,Y,False,Y
12,G4,35.0,LEX,4017.0,PIE,3617.0,NaN,0,320,4017,...,35,Allegiant Air,NaN,G4,AAY,ALLEGIANT,United States,Y,False,Y
13,G4,35.0,LEX,4017.0,SFB,4167.0,NaN,0,M80 320,4017,...,35,Allegiant Air,NaN,G4,AAY,ALLEGIANT,United States,Y,False,Y
14,KL,3090.0,LEX,4017.0,ATL,3682.0,Y,0,CR9 CRJ,4017,...,3090,KLM Royal Dutch Airlines,NaN,KL,KLM,KLM,Netherlands,Y,False,Y
15,UA,5209.0,LEX,4017.0,IAH,3550.0,Y,0,ERJ,4017,...,5209,United Airlines,NaN,UA,UAL,UNITED,United States,Y,False,Y
16,UA,5209.0,LEX,4017.0,ORD,3830.0,Y,0,ERJ CRJ,4017,...,5209,United Airlines,NaN,UA,UAL,UNITED,United States,Y,False,Y
17,US,5265.0,LEX,4017.0,CLT,3876.0,NaN,0,CR7,4017,...,5265,US Airways,NaN,US,USA,U S AIR,United States,Y,False,Y
18,US,5265.0,LEX,4017.0,DFW,3670.0,NaN,0,ERD,4017,...,5265,US Airways,NaN,US,USA,U S AIR,United States,Y,False,Y
19,US,5265.0,LEX,4017.0,ORD,3830.0,Y,0,ERD ER4,4017,...,5265,US Airways,NaN,US,USA,U S AIR,United States,Y,False,Y

5) Actually, it looks like a bunch of these routes are codeshares.  That means they are marketed by this airline, but operated by a different airline.  See the note in the data documentation on openflights.org/data.  The implication of this is that there are duplicates.

Can you figure out which ones are duplicates?  Can you then create a dataframe with only the unique routes?  How many unique inbound and outbound routes are there? 

Remember, someone has to operate the flight, so if all the routes to/from a particular airport are listed as codeshares, then something is funny...

It is also possible that more than one airline actually operates a route between the same two airports. (Having this sort of competition generally means that you will get better fares as a traveler.)  It may not be obvious what is actually in the data set, so dig or do external research as needed.

In [19]:
lex_routes = lex_routes.drop(['source_y','source'], axis=1)
lex_routes = lex_routes.rename(columns={'source_x': 'source'})

In [20]:

lex_routes = lex_routes.drop_duplicates(subset=['source', 'dest'])
lex_routes

,airline,airline_id,source,source_id,dest,dest_id,codeshare,stops,equipment,id_source,...,country_dest,iata_dest,icao_dest,latitude_dest,longitude_dest,altitude_dest,timezone_dest,dst_dest,tz_dest,type_dest
0,9E,3976.0,LEX,4017.0,ATL,3682.0,NaN,0,CRJ,4017,...,United States,ATL,KATL,33.636700,-84.428101,1026,-5.0,A,America/New_York,airport
1,AA,24.0,LEX,4017.0,CLT,3876.0,Y,0,CR7 CRJ,4017,...,United States,CLT,KCLT,35.214001,-80.943100,748,-5.0,A,America/New_York,airport
2,AA,24.0,LEX,4017.0,DFW,3670.0,Y,0,ERD ER4,4017,...,United States,DFW,KDFW,32.896801,-97.038002,607,-6.0,A,America/Chicago,airport
3,AA,24.0,LEX,4017.0,ORD,3830.0,Y,0,ERD ER4,4017,...,United States,ORD,KORD,41.978600,-87.904800,672,-6.0,A,America/Chicago,airport
6,DL,2009.0,LEX,4017.0,DCA,3520.0,Y,0,CRJ,4017,...,United States,DCA,KDCA,38.852100,-77.037697,15,-5.0,A,America/New_York,airport
7,DL,2009.0,LEX,4017.0,DTW,3645.0,Y,0,CR7 CRJ CR9,4017,...,United States,DTW,KDTW,42.212399,-83.353401,645,-5.0,A,America/New_York,airport
8,DL,2009.0,LEX,4017.0,LGA,3697.0,NaN,0,ERJ,4017,...,United States,LGA,KLGA,40.777199,-73.872597,21,-5.0,A,America/New_York,airport
9,DL,2009.0,LEX,4017.0,MSP,3858.0,Y,0,CRJ,4017,...,United States,MSP,KMSP,44.882000,-93.221802,841,-6.0,A,America/Chicago,airport
10,G4,35.0,LEX,4017.0,FLL,3533.0,NaN,0,M80,4017,...,United States,FLL,KFLL,26.072599,-80.152702,9,-5.0,A,America/New_York,airport
11,G4,35.0,LEX,4017.0,PGD,7056.0,NaN,0,M80,4017,...,United States,PGD,KPGD,26.920200,-81.990501,26,-5.0,A,America/New_York,airport
12,G4,35.0,LEX,4017.0,PIE,3617.0,NaN,0,320,4017,...,United States,PIE,KPIE,27.910200,-82.687401,11,-5.0,A,America/New_York,airport
13,G4,35.0,LEX,4017.0,SFB,4167.0,NaN,0,M80 320,4017,...,United States,SFB,KSFB,28.777599,-81.237503,55,-5.0,A,America/New_York,airport
15,UA,5209.0,LEX,4017.0,IAH,3550.0,Y,0,ERJ,4017,...,United States,IAH,KIAH,29.984400,-95.341400,97,-6.0,A,America/Chicago,airport

In [28]:
In_airline_LEX_unique= airline_LEX[airline_LEX['codeshare']!='Y']
len(In_airline_LEX_unique)
In_airline_LEX_unique

,airline,airline_id,source_x,source_id,dest,dest_id,codeshare,stops,equipment,id_source,...,source,id,name,alias,iata,icao,callsign,country,active,International
0,9E,3976.0,LEX,4017.0,ATL,3682.0,NaN,0,CRJ,4017,...,OurAirports,3976,Pinnacle Airlines,NaN,9E,FLG,FLAGSHIP,United States,Y,False
5,DL,2009.0,LEX,4017.0,ATL,3682.0,NaN,0,M88 717,4017,...,OurAirports,2009,Delta Air Lines,NaN,DL,DAL,DELTA,United States,Y,False
8,DL,2009.0,LEX,4017.0,LGA,3697.0,NaN,0,ERJ,4017,...,OurAirports,2009,Delta Air Lines,NaN,DL,DAL,DELTA,United States,Y,False
10,G4,35.0,LEX,4017.0,FLL,3533.0,NaN,0,M80,4017,...,OurAirports,35,Allegiant Air,NaN,G4,AAY,ALLEGIANT,United States,Y,False
11,G4,35.0,LEX,4017.0,PGD,7056.0,NaN,0,M80,4017,...,OurAirports,35,Allegiant Air,NaN,G4,AAY,ALLEGIANT,United States,Y,False
12,G4,35.0,LEX,4017.0,PIE,3617.0,NaN,0,320,4017,...,OurAirports,35,Allegiant Air,NaN,G4,AAY,ALLEGIANT,United States,Y,False
13,G4,35.0,LEX,4017.0,SFB,4167.0,NaN,0,M80 320,4017,...,OurAirports,35,Allegiant Air,NaN,G4,AAY,ALLEGIANT,United States,Y,False
17,US,5265.0,LEX,4017.0,CLT,3876.0,NaN,0,CR7,4017,...,OurAirports,5265,US Airways,NaN,US,USA,U S AIR,United States,Y,False
18,US,5265.0,LEX,4017.0,DFW,3670.0,NaN,0,ERD,4017,...,OurAirports,5265,US Airways,NaN,US,USA,U S AIR,United States,Y,False